name: my-wonderful-API

on:
  push:
    branches:
      - main
    paths:
    - 'API.sln'
    - 'Application/**'
    - 'AzureConfigurations/**'
    - 'Domain/**'
    - 'Interface/**'
    - 'Repository/**'
    - 'API/**'
  workflow_dispatch:

env:
  APPNAME_NAME: 'my-wonderful-API'
  SOLUTION_NAME: 'API.sln'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up .NET Core'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build with dotnet'
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release

      - name: 'Publish with dotnet'
        run: dotnet publish ${{ env.SOLUTION_NAME }} -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_315CC2A359844E6A9A80AB838CE43987 }}
          tenant-id: ${{ secrets.AZURETENANTID_1535A9C03FF4436C85A78878A56EF53D }}
          subscription-id: ${{ secrets.AZURESUBSCRIPTIONID_BF690D004BBE4C04AB1FA5D2F761ADCF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APPNAME_NAME }}
          slot-name: 'Production'
          package: .
          
